return [
    'Section in State of Environment report',
    'Environmental statistics',
    'Environmental indicator set',
    'Environmental compendium',
    'Section in environmental performance review',
    'State of water assessment/report',
    'Water statistics',
    'Water indicator set',
    'Water sector or NGOs report',
    'Library services',
    'Country profiles',
    'Website',
    'National Institution dealing with water',
]
