METATYPE_TALKBACKCONSULTATION = 'Naaya TalkBack Consultation'
METATYPE_TALKBACKCONSULTATION_SECTION = 'Naaya TalkBack Consultation Section'
METATYPE_TALKBACKCONSULTATION_PARAGRAPH = 'Naaya TalkBack Consultation Paragraph'
METATYPE_TALKBACKCONSULTATION_COMMENT = 'Naaya TalkBack Consultation Comment'

PERMISSION_REVIEW_TALKBACKCONSULTATION = 'Naaya - Review TalkBack Consultation'
PERMISSION_MANAGE_TALKBACKCONSULTATION = 'Naaya - Manage TalkBack Consultation'
PERMISSION_INVITE_TO_TALKBACKCONSULTATION = 'Naaya - Invite to TalkBack Consultation'
