EIONET_SURVEY_ID = 'eionet-survey'
EIONET_SURVEY_TITLE = 'Eionet evaluation survey'
EIONET_SURVEY_QUESTIONS = [
    {'meta_type': 'Naaya Radio Widget',
     'title': '1.1. I am',
     'choices': ['National Reference Centre', 'National Focal Point',
                'European Topic Centre', 'Other Participant'],
     'sortorder': 1,
     'required': True},
    {'meta_type': 'Naaya Radio Widget',
     'title': '1.2. Have you attended previous Eionet workshops?',
     'choices': ['None', '1-3 times', '4-10 times', 'More than 10 times'],
     'sortorder': 2,
     'required': True},
    {'meta_type': 'Naaya Radio Widget',
     'title': '2.1. How did you find the workshop overall?',
     'choices': ['Poor', 'Satisfactory', 'Good', 'Excellent'],
     'sortorder': 3,
     'required': True},
    {'meta_type': 'Naaya Radio Matrix Widget',
     'title': '2.2. Agenda and objectives',
     'choices': ['Poor', 'Satisfactory', 'Good', 'Excellent'],
     'rows': ['2.2.1 Are the objectives of the workshop clear?',
              '2.2.2 Is the agenda of the workshop clear?',
              '2.2.3 Is the background material useful?',
              '2.2.4 Was the right mix of topics covered?',
              ('2.2.5 Were the background documents useful to you in your '
                  'daily job?'),
              ('2.2.6 Did you share the documents or other information with '
                  'your colleagues?'),
              '2.2.7 Were the objectives of the workshop achieved?'],
     'sortorder': 4,
     'required': True},
    {'meta_type': 'Naaya Radio Matrix Widget',
     'title': '3. Workshop content and programme',
     'choices': ['Poor', 'Satisfactory', 'Good', 'Excellent'],
     'rows': ['3.1 Relevance of the agenda for your work',
              '3.2 Balance of content between European and country level',
              '3.3 Facilitation / Chairing (if applicable)',
              '3.4 Use of practical examples/ case studies',
              '3.5 Quality of presentations',
              '3.6 Engagement with ETC partners, if applicable',
              '3.7 Exchange of information and  experiences'],
     'sortorder': 5,
     'required': True},
    {'meta_type': 'Naaya Text Area Widget',
     'title': '4. Further comments on the above',
     'tooltips': ('(e.g. time for country experiences, usefulness '
                  'of specific presentations etc.)'),
     'sortorder': 6,
     'rows': 5},
    {'meta_type': 'Naaya Radio Matrix Widget',
     'title': '5. Organisational aspects',
     'choices': ['Poor', 'Satisfactory', 'Good', 'Excellent'],
     'rows': ['5.1 Travel arrangements prior to workshop',
              '5.2 Secretariat support',
              ('5.3 Working conditions during this workshop '
                  '(conference room facilities, equipment etc.)'),
              '5.4 Convenience of the location'],
     'sortorder': 7,
     'required': True},
    {'meta_type': 'Naaya Radio Matrix Widget',
     'title': '6. Time allocation',
     'choices': ['Too short', 'Fine', 'Too long'],
     'rows': ['6.1 Length of the Eionet workshop',
              '6.2 Length of time allocated to  discussions and Q&A',
              '6.3 Length of time allocated to country level experiences',
              '6.4 Time for networking including social events'],
     'sortorder': 8,
     'required': True},
    {'meta_type': 'Naaya Text Area Widget',
     'title': ('7. Please name the 3 most valuable pieces of '
               'information you have gained from this workshop.'),
     'sortorder': 9,
     'rows': 5},
    {'meta_type': 'Naaya Radio Widget',
     'title': ('8.1 Ideas for further improving Eionet workshops '
               '- Address additional topics?'),
     'choices': ['Yes', 'No'],
     'sortorder': 10,
     'required': True},
    {'meta_type': 'Naaya Text Area Widget',
     'title': 'If yes, please specify',
     'sortorder': 11,
     'rows': 5},
    {'meta_type': 'Naaya Radio Widget',
     'title': ('8.2 Do you consider communication between EEA and '
               'NRCs between workshops sufficient?'),
     'choices': ['Yes', 'No'],
     'sortorder': 12,
     'required': True},
    {'meta_type': 'Naaya Text Area Widget',
     'title': 'If no, please provide suggestions',
     'sortorder': 13,
     'rows': 5},
    {'meta_type': 'Naaya Checkboxes Widget',
     'title': ('8.3 Which forms of communication do you prefer '
               'between Eionet workshops?'),
     'choices': ['eMail', 'Eionet Forum', 'Social media platforms', 'Webinar',
                'Newsletter'],
     'sortorder': 14, 'required': True},
    {'meta_type': 'Naaya Text Area Widget',
     'title': 'Any additional comments',
     'tooltips': ('(e.g. unintended benefits, the most positive '
                  'or negative aspects)'),
     'sortorder': 15,
     'rows': 5},
]
