//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CHM2.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CHM2_DIALOG                 102
#define IDS_ABORT_WIZARD_CAPTION        102
#define IDS_COPY_DIRECTORY              103
#define IDS_FAILED_COPY_DIRECTORY       104
#define IDS_FAILED_COPY_FILE            105
#define IDS_ERROR_OPEN_FILE             106
#define IDS_ABORT_WIZARD_MESSAGE        107
#define IDS_AGREEMENT                   108
#define IDS_ACCEPT_AGREEMENT            109
#define IDS_RUN_SERVICE                 110
#define IDS_RUN_MANUAL                  111
#define IDS_SUMMARY                     112
#define IDS_MENU_FOLDER_NAME            113
#define IDS_INSTALLATION_START          114
#define IDS_FILE_LOG                    115
#define IDS_LABEL_END_INSTALL           116
#define IDS_INSTALLATION_COMPLETE       117
#define IDS_REMOVING_FILES              118
#define IDS_DELETE_INSTALLATION_FILES   119
#define IDS_FOLDER_ZOPE                 120
#define IDS_FOLDER_BIN                  121
#define IDS_FAIL_INSTALL                123
#define IDS_LABEL_BEGIN_INSTALL         124
#define IDS_LABEL_NORIGHTS              125
#define IDS_START_COPY                  126
#define IDS_FAIL_COPY                   127
#define IDR_MAINFRAME                   128
#define IDS_END_COPY                    128
#define IDW_ERROR                       129
#define IDS_START_CONFIGURE             129
#define IDW_WELCOME                     130
#define IDS_FAIL_CONFIGURE              130
#define IDW_AGREEMENT                   131
#define IDS_END_CONFIGURE               131
#define IDW_INSTALLPATH                 132
#define IDS_START_RUNSCRIPTS            132
#define IDW_PARAMETERS                  133
#define IDS_FAIL_RUNSCRIPTS             133
#define IDW_PORTS                       134
#define IDS_END_RUNSCRIPTS              134
#define IDW_FINISH                      135
#define IDS_START_CLEANUP               135
#define IDW_INSTALL                     136
#define IDS_FAIL_CLEANUP                136
#define IDS_END_CLEANUP                 137
#define IDB_SETUP                       138
#define IDS_START_UPDATEREGISTRY        138
#define IDS_END_UPDATEREGISTRY          139
#define IDW_PORTALMETADATA              139
#define IDS_COPY_ZOPE                   140
#define IDW_PORTALADMINISTRATIVE        140
#define IDS_FAILED_CREATE_DIRECTORY     141
#define IDW_PORTALLOGOS                 141
#define IDS_COPY_BIN                    142
#define IDS_MOVE_FILE                   144
#define IDS_FAILED_MOVE_FILE            145
#define IDS_COPY_FILE                   146
#define IDS_CONFIGURE_FILE              147
#define IDS_EXECUTE_COMMAND             148
#define IDS_DELETE_FILE                 149
#define IDS_FAILED_DELETE_FILE          150
#define IDS_LABEL_START_CREATESHORTCUTS 151
#define IDS_LABEL_END_CREATESHORTCUTS   153
#define IDS_REGCOMPANY                  154
#define IDS_REGAPPLICATION              155
#define IDS_AVAILABLESPACE              156
#define IDS_REQUIREDSPACE               157
#define IDS_INSTALLATION_DEFAULT_PATH   158
#define IDS_CREATEDIRECTORY_QUESTION    159
#define IDS_CREATEDIRECTORY             160
#define IDS_ERROR_CREATE_DIR            161
#define IDS_NOTENOUGHSPACE              162
#define IDS_INVALIDPATH                 163
#define IDS_DEFAULT_ADMINISTRATOREMAIL  164
#define IDS_REQUIREDFIELDS              165
#define IDS_USERNAME_ALPHANUMERIC       166
#define IDS_PASSWORD_ALPHANUMERIC       167
#define IDS_PASSWORDS                   168
#define IDS_DEFAULT_ZOPEHTTPPORT        169
#define IDS_DEFAULT_ZOPEFTPPORT         170
#define IDS_DEFAULT_ZOPEWEBDAVPORT      171
#define IDS_ZOPEHTTPPORT_INVALID        172
#define IDS_ZOPEHTTPPORT_OCCUPIED       173
#define IDS_ZOPEFTPPORT_INVALID         174
#define IDS_ZOPEFTPPORT_OCCUPIED        175
#define IDS_ZOPEWEBDAVPORT_INVALID      176
#define IDS_ZOPEWEBDAVPORT_OCCUPIED     177
#define IDS_SERVICE_NAME_ZOPE           178
#define IDS_SERVICE_ALREADY_INSTALLED   179
#define IDS_REGISTRY_TELLS              180
#define IDS_SHORTCUT_ALREADY_EXISTS     181
#define IDS_LABEL_EXIT_BUTTON           182
#define IDS_FOLDER_INSTANCE             183
#define IDS_COPY_INSTANCE               184
#define IDS_SHORTCUT_CHM2_NAME          185
#define IDS_SHORTCUT_CHM2_DESCRIPTION   186
#define IDS_CREATE_SHORTCUT             187
#define IDS_SHORTCUT_CONSOLE_NAME       188
#define IDS_SHORTCUT_CONSOLE_DESCRIPTION 189
#define IDS_SHORTCUT_UNINSTALL_NAME     190
#define IDS_SHORTCUT_UNINSTALL_DESCRIPTION 191
#define IDS_MAILSERVERPORT_INVALID      192
#define IDS_DATASOURCE_IMAGEFILES       193
#define IDS_COPY_LOGO                   194
#define IDC_SHEETRECT                   1004
#define IDC_AGREEMENT_TITLE             1005
#define IDC_AGREEMENT_INFORMATION       1006
#define IDC_AGREEMENT_RB_ACCEPT         1007
#define IDC_AGREEMENT_RB_DECLINE        1008
#define IDC_ERROR_TITLE                 1009
#define IDC_ERROR_SUMMARY_EDIT          1010
#define IDS_FINISH_TITLE                1011
#define IDC_FINISH_TITLE                1011
#define IDC_FINISH_SUMMARY_EDIT         1012
#define IDC_INSTALL_TITLE               1013
#define IDC_STATIC_INFO                 1014
#define IDC_PROGRESS_INSTALLATION       1015
#define IDC_STATIC_INSTALLATION         1016
#define IDC_CHECK_START                 1017
#define IDC_INSTALLPATH_TITLE           1018
#define IDC_INSTALLPATH_PATH_EDIT       1019
#define IDC_INSTALLPATH_BROWSE_BUTTON   1020
#define IDC_INSTALLPATH_AVAILABLESPACE_LABEL 1021
#define IDC_INSTALLPATH_AVAILABLESPACE_VALUE 1022
#define IDC_INSTALLPATH_REQUIREDSPACE_LABEL 1023
#define IDC_INSTALLPATH_REQUIREDSPACE_VALUE 1024
#define IDC_PARAMETERS_TITLE            1025
#define IDC_PARAMETERS_FULLHOSTNAME_EDIT 1026
#define IDC_PARAMETERS_HOSTIDADDRESS_IPADDRESS 1027
#define IDC_PARAMETERS_USERNAME_EDIT    1028
#define IDC_PARAMETERS_PASSWORD_EDIT    1029
#define IDC_PARAMETERS_CONFIRMPASSWORD_EDIT 1030
#define IDC_PARAMETERS_ADMINEMAIL_EDIT  1031
#define IDC_PORTS_TITLE                 1032
#define IDC_PORTS_ZOPEHTTPPORT_EDIT     1033
#define IDC_PORTS_ZOPEFTPPORT_EDIT      1034
#define IDC_PORTS_ZOPEWEBDAVPORT_EDIT   1035
#define IDC_WELCOME_TITLE               1036
#define IDC_PORTAL_TITLE                1037
#define IDC_PORTAL_SUBTITLE             1039
#define IDC_PORTAL_PUBLISHER            1040
#define IDC_PORTAL_CONTRIBUTOR          1041
#define IDC_PORTAL_CREATOR              1042
#define IDC_PORTAL_RIGHTS               1043
#define IDC_PORTALMETADATA_TITLE        1044
#define IDC_PORTALADMINISTRATIVE_TITLE  1045
#define IDC_PORTAL_LANGUAGES            1048
#define IDC_PORTAL_URL                  1049
#define IDC_PORTAL_MAILSERVERNAME       1050
#define IDC_PORTAL_MAILSERVERPORT       1051
#define IDC_LOGO_PATH                   1051
#define IDC_PORTAL_DEFAULTFROMADDRESS   1052
#define IDC_LOGO_BROWSE_BUTTON          1052
#define IDC_LOGOBIS_PATH                1053
#define IDC_LOGOBIS_BROWSE_BUTTON       1054
#define IDC_PORTALLOGOS_TITLE           1055

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
