REF_TREES = [
    ('gstc_criteria',
        {'GSTCDA': 'A. Sustainable Management',
         'GSTCDA1': 'A.1. Management System',
         'GSTCDA2': 'A.2. Legal Compliance',
         'GSTCDA3': 'A.3. Employee Training',
         'GSTCDA4': 'A.4. Customer Satisfaction',
         'GSTCDA5': 'A.5. Marketing Accuracy',
         'GSTCDA6':
            'A.6. Design and construction of buildings and infrastructure',
         'GSTCDA6_1': 'A.6.1. Zoning',
         'GSTCDA6_2': 'A.6.2. Design and Siting',
         'GSTCDA6_3': 'A.6.3. Sustainable Construction',
         'GSTCDA6_4': 'A.6.4. Special Needs Access',
         'GSTCDA7': 'A.7. Interpretation',
         'GSTCDB': 'B. Social/Economic',
         'GSTCDB1': 'B.1. Community Development',
         'GSTCDB2': 'B.2. Local Employment',
         'GSTCDB3': 'B.3. Fair-Trade',
         'GSTCDB4': 'B.4. Local Entrepreneurs',
         'GSTCDB5': 'B.5. Indigenous Communities',
         'GSTCDB6': 'B.6. Exploitation',
         'GSTCDB7': 'B.7. Equitable Hiring',
         'GSTCDB8': 'B.8. Employee Protection',
         'GSTCDB9': 'B.9. Basic Services',
         'GSTCDC': 'C. Cultural Heritage',
         'GSTCDC1': 'C.1. Code of Behavior',
         'GSTCDC2': 'C.2. Historical Artifacts',
         'GSTCDC3': 'C.3. Protection of Sites',
         'GSTCDC4': 'C.4. Incorporation of Culture',
         'GSTCDD': 'D. Environment',
         'GSTCDD1': 'D.1. Conserving resources',
         'GSTCDD1_1': 'D.1.1. Purchasing Policy',
         'GSTCDD1_2': 'D.1.2. Consumable Goods',
         'GSTCDD1_3': 'D.1.3. Energy Consumption',
         'GSTCDD1_4': 'D.1.4. Water Consumption',
         'GSTCDD2': 'D.2. Reducing Pollution',
         'GSTCDD2_1': 'D.2.1. Greenhouse Gas',
         'GSTCDD2_2': 'D.2.2. Wastewater',
         'GSTCDD2_3': 'D.2.3. Waste Management Plan',
         'GSTCDD2_4': 'D.2.4. Harmful Substances',
         'GSTCDD2_5': 'D.2.5. Other Pollutants',
         'GSTCDD3': 'D.3. Conserving biodiversity, ecosystems, and landscapes',
         'GSTCDD3_1': 'D.3.1. Wildlife Species',
         'GSTCDD3_2': 'D.3.2. Wildlife in Captivity',
         'GSTCDD3_3': 'D.3.3. Landscaping',
         'GSTCDD3_4': 'D.3.4. Biodiversity Conservation',
         'GSTCDD3_5': 'D.3.5. Interactions with Wildlife',
         }
     ),
]
