# coding=utf-8
return {
'Section in State of Environment report': ['Section in State of Environment report'],
'Section in environmental performance review': ['Section in environmental performance review'],
'State of water assessment/report': ['State of water assessment/report – National level',
                                     'State of water assessment/report – Sub-national level',
                                     'State of water assessment/report – Regional/Global level'],
'Green economy assessment/report': ['State of green economy assessment/report – National level',
                                             'State of green economy assessment/report – Sub-national level',
                                             'State of green economy assessment/report – Regional/Global level'],
'Sectorial report': ['Sectorial report'],
'Water sector or NGOs report': ['Water sector or NGOs report'],
'Water statistics': ['Water statistics'],
'Environmental statistics': ['Environmental statistics'],
'Environmental indicator set': ['Environmental indicator set – National',
                                'Environmental indicator set – Sub-national',
                                'Environmental indicator set – Regional'],
'Environmental compendium': ['Environmental compendium'],
'Water indicator set': ['Water indicator set'],
'Website': ['Website'],
'Library services': ['Library services'],
'Country profiles': ['Country profiles'],
'National Institution dealing with water': ['National Institution dealing with water'],
'National Institution dealing with green economy': ['National Institution dealing with green economy'],
}
