//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PTKInstaller.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PTKINSTALLER_DIALOG         102
#define IDS_ABORT_WIZARD_CAPTION        102
#define IDS_SERVICE_NAME_ZOPE           103
#define IDS_SERVICE_ALREADY_INSTALLED   104
#define IDS_FOLDER_ZOPE                 105
#define IDS_FOLDER_BIN                  106
#define IDS_COPY_DIRECTORY              107
#define IDS_FAILED_COPY_DIRECTORY       108
#define IDS_FAILED_COPY_FILE            109
#define IDS_ERROR_OPEN_FILE             110
#define IDS_REGCOMPANY                  111
#define IDS_REGAPPLICATION              112
#define IDS_REGISTRY_TELLS              113
#define IDS_MENU_FOLDER_NAME            114
#define IDS_SHORTCUT_ALREADY_EXISTS     115
#define IDS_LABEL_EXIT_BUTTON           116
#define IDS_ABORT_WIZARD_MESSAGE        117
#define IDS_AGREEMENT                   118
#define IDS_ACCEPT_AGREEMENT            119
#define IDS_INSTALLATION_DEFAULT_PATH   120
#define IDS_CREATEDIRECTORY_QUESTION    121
#define IDS_CREATEDIRECTORY             122
#define IDS_NOTENOUGHSPACE              123
#define IDS_ERROR_CREATE_DIR            124
#define IDS_INVALIDPATH                 125
#define IDS_AVAILABLESPACE              126
#define IDS_REQUIREDSPACE               127
#define IDR_MAINFRAME                   128
#define IDS_REQUIREDFIELDS              128
#define IDW_WELCOME                     129
#define IDS_USERNAME_ALPHANUMERIC       129
#define IDB_SETUP                       130
#define IDS_PASSWORD_ALPHANUMERIC       130
#define IDW_ERROR                       131
#define IDS_PASSWORDS                   131
#define IDW_AGREEMENT                   132
#define IDS_DEFAULT_ZOPEHTTPPORT        132
#define IDW_INSTALLPATH                 133
#define IDS_ZOPEHTTPPORT_INVALID        133
#define IDW_PARAMETERS                  134
#define IDS_ZOPEHTTPPORT_OCCUPIED       134
#define IDW_PORTS                       135
#define IDS_MAILSERVERPORT_INVALID      135
#define IDW_METADATA                    136
#define IDS_RUN_SERVICE                 136
#define IDW_ADMINISTRATIVE              137
#define IDS_RUN_MANUAL                  137
#define IDW_PORTALADMINISTRATIVE        138
#define IDS_SUMMARY                     138
#define IDW_SUMMARY                     139
#define IDS_INSTALLATION_START          139
#define IDW_INSTALL                     140
#define IDS_FILE_LOG                    140
#define IDS_LABEL_END_INSTALL           141
#define IDS_INSTALLATION_COMPLETE       142
#define IDS_REMOVING_FILES              143
#define IDS_DELETE_INSTALLATION_FILES   144
#define IDS_FAIL_INSTALL                145
#define IDS_FOLDER_INSTANCE             146
#define IDS_LABEL_BEGIN_INSTALL         147
#define IDS_LABEL_NORIGHTS              148
#define IDS_START_COPY                  149
#define IDS_FAIL_COPY                   150
#define IDS_END_COPY                    151
#define IDS_START_CONFIGURE             152
#define IDS_FAIL_CONFIGURE              153
#define IDS_END_CONFIGURE               154
#define IDS_START_RUNSCRIPTS            155
#define IDS_FAIL_RUNSCRIPTS             156
#define IDS_END_RUNSCRIPTS              157
#define IDS_START_CLEANUP               158
#define IDS_FAIL_CLEANUP                159
#define IDS_END_CLEANUP                 160
#define IDS_START_UPDATEREGISTRY        161
#define IDS_END_UPDATEREGISTRY          162
#define IDS_COPY_ZOPE                   163
#define IDS_FAILED_CREATE_DIRECTORY     164
#define IDS_COPY_INSTANCE               165
#define IDS_COPY_BIN                    166
#define IDS_MOVE_FILE                   167
#define IDS_FAILED_MOVE_FILE            168
#define IDS_CONFIGURE_FILE              169
#define IDS_EXECUTE_COMMAND             170
#define IDS_DELETE_FILE                 171
#define IDS_FAILED_DELETE_FILE          172
#define IDS_LABEL_START_CREATESHORTCUTS 173
#define IDS_LABEL_END_CREATESHORTCUTS   174
#define IDS_CREATE_SHORTCUT             175
#define IDS_SHORTCUT_CONSOLE_NAME       176
#define IDS_SHORTCUT_CONSOLE_DESCRIPTION 177
#define IDS_SHORTCUT_UNINSTALL_NAME     178
#define IDS_SHORTCUT_UNINSTALL_DESCRIPTION 179
#define IDS_SHORTCUT_PTK_NAME           180
#define IDS_SHORTCUT_PTK_DESCRIPTION    181
#define IDC_SHEETRECT                   1003
#define IDC_WELCOME_TITLE               1004
#define IDC_ERROR_TITLE                 1005
#define IDC_ERROR_SUMMARY_EDIT          1006
#define IDC_AGREEMENT_TITLE             1007
#define IDC_AGREEMENT_INFORMATION       1008
#define IDC_AGREEMENT_RB_ACCEPT         1009
#define IDC_AGREEMENT_RB_DECLINE        1010
#define IDC_INSTALLPATH_TITLE           1011
#define IDC_INSTALLPATH_PATH_EDIT       1012
#define IDC_INSTALLPATH_BROWSE_BUTTON   1013
#define IDC_INSTALLPATH_AVAILABLESPACE_LABEL 1014
#define IDC_INSTALLPATH_AVAILABLESPACE_VALUE 1015
#define IDC_INSTALLPATH_REQUIREDSPACE_LABEL 1016
#define IDC_INSTALLPATH_REQUIREDSPACE_VALUE 1017
#define IDC_PARAMETERS_TITLE            1018
#define IDC_PARAMETERS_FULLHOSTNAME_EDIT 1019
#define IDC_PARAMETERS_HOSTIDADDRESS_IPADDRESS 1020
#define IDC_PARAMETERS_USERNAME_EDIT    1021
#define IDC_PARAMETERS_PASSWORD_EDIT    1022
#define IDC_PARAMETERS_CONFIRMPASSWORD_EDIT 1023
#define IDC_PARAMETERS_ADMINEMAIL_EDIT  1024
#define IDC_PORTS_TITLE                 1025
#define IDC_PORTS_ZOPEHTTPPORT_EDIT     1026
#define IDC_PORTALMETADATA_TITLE        1027
#define IDC_PORTAL_TITLE                1028
#define IDC_PORTAL_SUBTITLE             1029
#define IDC_PORTAL_PUBLISHER            1030
#define IDC_PORTAL_CONTRIBUTOR          1031
#define IDC_PORTAL_CREATOR              1032
#define IDC_PORTAL_RIGHTS               1033
#define IDC_PORTALADMINISTRATIVE_TITLE  1034
#define IDC_PORTAL_LANGUAGES            1035
#define IDC_PORTAL_MAILSERVERNAME       1036
#define IDC_PORTAL_MAILSERVERPORT       1037
#define IDC_PORTAL_DEFAULTFROMADDRESS   1038
#define IDC_SUMMARY_TITLE               1039
#define IDC_SUMMARY_EDIT                1040
#define IDC_INSTALL_TITLE               1041
#define IDC_STATIC_INFO                 1042
#define IDC_PROGRESS_INSTALLATION       1043
#define IDC_STATIC_INSTALLATION         1044
#define IDC_CHECK_START                 1045

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
