METATYPE_TALKBACKCONSULTATION = 'Naaya TalkBack Consultation'
METATYPE_TALKBACKCONSULTATION_SECTION = 'Naaya TalkBack Consultation Section'
METATYPE_TALKBACKCONSULTATION_PARAGRAPH = 'Naaya TalkBack Consultation Paragraph'
METATYPE_TALKBACKCONSULTATION_COMMENT = 'Naaya TalkBack Consultation Comment'
