KEYWORD_INDEXES = ['gstc_criteria']

REF_TREES = [
    ('gstc_criteria',
        [('GSTCDA', 'A. Management'),
         ('GSTCDA1', 'A.1. Sustainable destination strategy'),
         ('GSTCDA2', 'A.2. Destination management organization'),
         ('GSTCDA3', 'A.3. Monitoring'),
         ('GSTCDA4', 'A.4. Tourism seasonality management'),
         ('GSTCDA5', 'A.5. Climate change adaptation'),
         ('GSTCDA6', 'A.6. Inventory of tourism assets and attractions'),
         ('GSTCDA7', 'A.7. Planning Regulations'),
         ('GSTCDA8', 'A.8. Access for all'),
         ('GSTCDA9', 'A.9. Property acquisitions'),
         ('GSTCDA10', 'A.10. Visitor satisfaction'),
         ('GSTCDA11', 'A.11. Sustainability standards'),
         ('GSTCDA12', 'A.12. Safety and security'),
         ('GSTCDA13', 'A.13. Crisis and emergency management'),
         ('GSTCDA14', 'A.14. Promotion'),
         ('GSTCDB', 'B. Socio-Economic'),
         ('GSTCDB1', 'B.1. Economic monitoring'),
         ('GSTCDB2', 'B.2. Local career opportunities'),
         ('GSTCDB3', 'B.3. Public participation'),
         ('GSTCDB4', 'B.4. Local community opinion'),
         ('GSTCDB5', 'B.5. Local access'),
         ('GSTCDB6', 'B.6. Tourism awareness and education'),
         ('GSTCDB7', 'B.7. Preventing exploitation'),
         ('GSTCDB8', 'B.8. Support for community'),
         ('GSTCDB9', 'B.9. Supporting local entrepreneurs and fair trade'),
         ('GSTCDC', 'C. Cultural'),
         ('GSTCDC1', 'C.1. Attraction protection'),
         ('GSTCDC2', 'C.2. Visitor management'),
         ('GSTCDC3', 'C.3. Visitor behavior'),
         ('GSTCDC4', 'C.4. Cultural heritage protection'),
         ('GSTCDC5', 'C.5. Site interpretation'),
         ('GSTCDC6', 'C.6. Intellectual property'),
         ('GSTCDD', 'D. Environmental'),
         ('GSTCDD1', 'D.1. Environmental risks'),
         ('GSTCDD2', 'D.2. Protection of sensitive environments'),
         ('GSTCDD3', 'D.3. Wildlife protection'),
         ('GSTCDD4', 'D.4. Greenhouse gas emissions'),
         ('GSTCDD5', 'D.5. Energy conservation'),
         ('GSTCDD6', 'D.6. Water Management'),
         ('GSTCDD7', 'D.7. Water security'),
         ('GSTCDD8', 'D.8. Water quality'),
         ('GSTCDD9', 'D.9. Wastewater'),
         ('GSTCDD10', 'D.10. Solid waste reduction'),
         ('GSTCDD11', 'D.11. Light and noise pollution'),
         ('GSTCDD12', 'D.12. Low-impact transportation'),
         ]
     ),
]
