return [
'Please select',
'Section in State of Environment report',
'Section in environmental performance review',
'State of water assessment/report – National level',
'State of water assessment/report – Sub-national level',
'State of water assessment/report – Regional level',
'State of green economy assessment/report – National level',
'State of green economy assessment/report – Sub-national level',
'State of green economy assessment/report – Regional level',
'Sectorial report',
'Water sector or NGOs report',
'Water statistics',
'Environmental statistics',
'Environmental indicator set – National',
'Environmental indicator set – Sub-national',
'Environmental indicator set – Regional',
'Environmental compendium',
'Water indicator set',
'Website',
'Library services',
'Country profiles',
'National Institution dealing with water',
'National Institution dealing with green economy',
]
