
import Globals


NAAYACONTENT_PRODUCT_NAME = 'NaayaContent'

DEFAULT_SORTORDER = 100

#other
MUST_BE_NONEMPTY =          1010
MUST_BE_DATETIME =          1020
MUST_BE_DATETIME_STRICT =   1030
MUST_BE_POSITIV_INT =       1040
MUST_BE_POSITIV_FLOAT =     1050
MUST_BE_CAPTCHA =           1060
