METATYPE_NYSURVEY = 'Naaya Survey'
METATYPE_NYSURVEY_TEMPLATE = 'Survey Template'
METATYPE_NYSURVEY_ANSWER = 'Survey Answer'

PREFIX_NYSURVEY = 'sv'
PREFIX_NYSURVEY_TEMPLATE = 'tp'
PREFIX_NYSURVEY_ANSWER = 'aw'

#permissions
PERMISSION_NYSURVEY_ADMINISTRATE = 'Naaya Survey - Manage'
PERMISSION_NYSURVEY_RESPOND = 'Naaya Survey - Post Answer'
